import _ from 'lodash'

const rawFoods = [
  {name:'acqua', unitMeasure:'kg', unitPrice:0.0000, vatCode: 0.0000, category: 'liquidi', avatar:'ingredients.png' },
  {name:'burro', unitMeasure:'kg', unitPrice:7.0000, vatCode: 0.0400, category: 'grassi', avatar:'ingredients.png' },
  {name:'cassonade', unitMeasure:'kg', unitPrice:6.0000, vatCode: 0.0400, category: 'zuccheri', avatar:'ingredients.png' },
  {name:'cioccolato fondente', unitMeasure:'kg', unitPrice:15.0000, vatCode: 0.1000, category: 'cioccolato', avatar:'ingredients.png' },
  {name:'cioccolato fondente 70%', unitMeasure:'kg', unitPrice:15.0000, vatCode: 0.1000, category: 'cioccolato', avatar:'ingredients.png' },
  {name:'farina 00 debole', unitMeasure:'kg', unitPrice:0.8000, vatCode: 0.0400, category: 'farine', avatar:'ingredients.png' },
  {name:'fondente bianco', unitMeasure:'kg', unitPrice:3.0000, vatCode: 0.1000, category: 'zuccheri', avatar:'ingredients.png' },
  {name:'latte', unitMeasure:'kg', unitPrice:1.1000, vatCode: 0.1000, category: 'latte', avatar:'ingredients.png' },
  {name:'panna fresca tigullio 38%', unitMeasure:'kg', unitPrice:3.8900, vatCode: 0.1000, category: 'grassi', avatar:'ingredients.png' },
  {name:'sale', unitMeasure:'kg', unitPrice:1.0000, vatCode: 0.0400, category: 'insaporitori', avatar:'ingredients.png' },
  {name:'tuorlo', unitMeasure:'kg', unitPrice:5.5500, vatCode: 0.1000, category: 'proteine', avatar:'ingredients.png' },
  {name:'uovo intero', unitMeasure:'kg', unitPrice:5.5500, vatCode: 0.1000, category: 'proteine', avatar:'ingredients.png' },
  {name:'zucchero semolato', unitMeasure:'kg', unitPrice:1.0000, vatCode: 0.0400, category: 'zuccheri', avatar:'ingredients.png' },
  {name:'bacca di vaniglia', unitMeasure:'kg', unitPrice:152.0000, vatCode: 0.2200, category: 'spezie circa 3 grammi a baccello', avatar:'ingredients.png'},
  {name:'amido di mais', unitMeasure:'kg', unitPrice:1.5000, vatCode: 0.1000, category: 'farine', avatar:'ingredients.png' },
  {name:'caffè macinato', unitMeasure:'kg', unitPrice:20.0000, vatCode: 0.1000, category: 'spezie', avatar:'ingredients.png' },
  {name:'zucchero a velo', unitMeasure:'kg', unitPrice:2.0000, vatCode: 0.0400, category: 'zuccheri', avatar:'ingredients.png' },
  {name:'rabarbaro pezzi congelato', unitMeasure:'kg', unitPrice:5.1000, vatCode: 0.1000, category: 'frutta in pezzi', avatar:'ingredients.png' },
  {name:'mango speziato purea congelato', unitMeasure:'kg', unitPrice:10.2000, vatCode: 0.1000, category: 'frutta purea', avatar:'ingredients.png' },
  {name:'fragola purea congelato', unitMeasure:'kg', unitPrice:6.8800, vatCode: 0.1000, category: 'frutta purea', avatar:'ingredients.png' },
  {name:'lampone purea congelato', unitMeasure:'kg', unitPrice:9.9500, vatCode: 0.1000, category: 'frutta purea', avatar:'ingredients.png' },
  {name:'ribes nero purea congelato', unitMeasure:'kg', unitPrice:7.9900, vatCode: 0.1000, category: 'frutta purea', avatar:'ingredients.png' },
  {name:'frutto passione purea congelato', unitMeasure:'kg', unitPrice:10.0300, vatCode: 0.1000, category: 'frutta purea', avatar:'ingredients.png' },
  {name:'lucidante in gel horeca select', unitMeasure:'kg', unitPrice:4.6100, vatCode: 0.1000, category: 'decorazioni', avatar:'ingredients.png' },
  {name:'pasta di mandorle', unitMeasure:'kg', unitPrice:9.5700, vatCode: 0.1000, category: 'paste', avatar:'ingredients.png' },
  {name:'burro Corman verde', unitMeasure:'kg', unitPrice:11.6000, vatCode: 0.0400, category: 'grassi', avatar:'ingredients.png' },
  {name:'albume', unitMeasure:'kg', unitPrice:5.5500, vatCode: 0.2200, category: 'liquidi', avatar:'ingredients.png' },
  {name:'gelatina in polvere', unitMeasure:'kg', unitPrice:33.0000, vatCode: 0.2200, category: 'gelatine', avatar:'ingredients.png' },
  {name:'zucchero invertito', unitMeasure:'kg', unitPrice:1.6700, vatCode: 0.0400, category: 'zuccheri', avatar:'ingredients.png' },
  {name:'succo di limone', unitMeasure:'kg', unitPrice:5.0000, vatCode: 0.2200, category: 'frutta succo', avatar:'ingredients.png' },
  {name:'pectina NH', unitMeasure:'kg', unitPrice:42.0000, vatCode: 0.0400, category: 'addensanti', avatar:'ingredients.png' },
  {name:'farina di mandorle', unitMeasure:'kg', unitPrice:12.0000, vatCode: 0.1000, category: 'farine', avatar:'ingredients.png' },
  {name:'fecola di patate', unitMeasure:'kg', unitPrice:1.3500, vatCode: 0.1000, category: 'farine', avatar:'ingredients.png' },
  {name:'amido di riso', unitMeasure:'kg', unitPrice:3.2600, vatCode: 0.1000, category: 'farine', avatar:'ingredients.png' },
  {name:'agar agar', unitMeasure:'kg', unitPrice:45.0000, vatCode: 0.2200, category: 'gelatine', avatar:'ingredients.png' },
  {name:'bianco uovo in polvere', unitMeasure:'kg', unitPrice:40.0000, vatCode: 0.2200, category: 'addensanti', avatar:'ingredients.png' },
  {name:'farina di farro integrale', unitMeasure:'kg', unitPrice:1.9800, vatCode: 0.1000, category: 'farine', avatar:'ingredients.png' },
  {name:'isomalto', unitMeasure:'kg', unitPrice:16.0000, vatCode: 0.0400, category: 'zuccheri', avatar:'ingredients.png' },
  {name:'pectina gialla', unitMeasure:'kg', unitPrice:35.0000, vatCode: 0.0400, category: 'addensanti', avatar:'ingredients.png' },
  {name:'Burro Corman BLU in placche', unitMeasure:'kg', unitPrice:6.9000, vatCode: 0.0400, category: 'grassi', avatar:'ingredients.png' },
  {name:'zenzero purea congelato', unitMeasure:'kg', unitPrice:11.0000, vatCode: 0.1000, category: 'frutta purea', avatar:'ingredients.png' },
  {name:'albicocca purea congelato', unitMeasure:'kg', unitPrice:5.6100, vatCode: 0.1000, category: 'frutta purea', avatar:'ingredients.png' },
  {name:'bicchiere monouso 350ml',unitMeasure:'pz', unitPrice: 0.2000, vatCode: 0.2200, category: 'imballi', avatar:'ingredients.png' },
  {name:'rosmarino fresco', unitMeasure:'kg', unitPrice:10.0000, vatCode: 0.2200, category: 'erbe aromatiche', avatar:'ingredients.png' },
  {name:'lievito di birra', unitMeasure:'kg', unitPrice:15.0000, vatCode: 0.0400, category: 'lieviti', avatar:'ingredients.png' },
  {name:'farina forte (W300)', unitMeasure:'kg', unitPrice:1.0000, vatCode: 0.0400, category: 'farine', avatar:'ingredients.png' },
  {name:'Cioccolato bianco', unitMeasure:'kg', unitPrice:12.0000, vatCode: 0.1000, category: 'cioccolato', avatar:'ingredients.png' },
  {name:'Estratto al caffè', unitMeasure:'kg', unitPrice:30.0000, vatCode: 0.2200, category: 'caffè', avatar:'ingredients.png' },
  {name:'Cioccolato Gianduia', unitMeasure:'kg', unitPrice:12.0000, vatCode: 0.1000, category: 'cioccolato', avatar:'ingredients.png' },
  {name:'Nocciole tostate', unitMeasure:'kg', unitPrice:15.0000, vatCode: 0.1000, category: 'frutta secca', avatar:'ingredients.png' },
  {name:'Nocciole', unitMeasure:'kg', unitPrice:25.0000, vatCode: 0.0400, category: 'frutta secca', avatar:'ingredients.png' },
  {name:'Burro di cacao', unitMeasure:'kg', unitPrice:30.0000, vatCode: 0.1000, category: 'cioccolato', avatar:'ingredients.png' },
  {name:'Cioccolato al latte', unitMeasure:'kg', unitPrice:12.0000, vatCode: 0.1000, category: 'cioccolato', avatar:'ingredients.png' },
  {name:'Pasta al caffè', unitMeasure:'kg', unitPrice:30.0000, vatCode: 0.2200, category: 'aromi in pasta', avatar:'ingredients.png' },
  {name:'Pasta di nocciola', unitMeasure:'kg', unitPrice:30.0000, vatCode: 0.2200, category: 'aromi in pasta', avatar:'ingredients.png' },
  {name:'Massa di cacao', unitMeasure:'kg', unitPrice:15.0000, vatCode: 0.1000, category: 'cioccolato', avatar:'ingredients.png' },
  {name:'Cacao Amaro in polvere', unitMeasure:'kg', unitPrice:13.0000, vatCode: 0.1000, category: 'cioccolato', avatar:'ingredients.png' },
  {name:'Tazzina caffè monouso', unitMeasure:'pz', unitPrice:0.1000, vatCode:0.2200, category:'imballi', avatar:'ingredients.png'},
  {name:'Caffè gourmet', unitMeasure:'kg', unitPrice:55.0000, vatCode: 0.1000, category: 'caffè', avatar:'ingredients.png' },
  {name:'Caffè normale', unitMeasure:'kg', unitPrice:25.0000, vatCode: 0.1000, category: 'caffè', avatar:'ingredients.png' },
  {name:'Acido citrico', unitMeasure:'kg', unitPrice:30.0000, vatCode: 0.1000, category: 'acidificanti', avatar:'ingredients.png'},
  {name:'Mora purea congelato', unitMeasure:'kg', unitPrice:10.7100, vatCode: 0.1000, category: 'frutta purea', avatar:'ingredients.png' },
  {name:'Aroma alla lavanda', unitMeasure:'kg', unitPrice:30.0000, vatCode: 0.2200, category: 'aromi', avatar:'ingredients.png' },
  {name:'Mirtillo purea congelato', unitMeasure:'kg', unitPrice:10.0000, vatCode: 0.1000, category: 'frutta purea', avatar:'ingredients.png' },
  {name:'Cocco rapee', unitMeasure:'kg', unitPrice:12.0000, vatCode: 0.2200, category: 'farine', avatar:'ingredients.png' },
  {name:'Pistacchio pelato', unitMeasure:'kg', unitPrice:25.0000, vatCode: 0.1000, category: 'frutta secca', avatar:'ingredients.png' },
  {name:'rum bianco agricolo', unitMeasure:'kg', unitPrice:40.0000, vatCode: 0.2200, category: 'superalcoolici', avatar:'ingredients.png' },
  {name:'Cocco purea congelato', unitMeasure:'kg', unitPrice:10.0000, vatCode: 0.1000, category: 'frutta purea', avatar:'ingredients.png' },
  {name:'Zeste di arancia', unitMeasure:'kg', unitPrice:17.0000, vatCode: 0.0400, category: 'frutta', avatar:'ingredients.png' },
  {name:'Zeste di limone', unitMeasure:'kg', unitPrice:17.0000, vatCode: 0.0400, category: 'frutta', avatar:'ingredients.png' },
  {name:'Foglie di menta', unitMeasure:'kg', unitPrice:30.0000, vatCode: 0.1000, category: 'erbe aromatiche', avatar:'ingredients.png' },
  {name:'Ananas sgocciolato in bastoncini', unitMeasure:'kg', unitPrice:5.0000, vatCode: 0.1000, category: 'Frutta fresca', avatar:'ingredients.png' },
  {name:'Coriandolo fresco', unitMeasure:'kg', unitPrice:20.0000, vatCode: 0.1000, category: 'erbe aromatiche', avatar:'ingredients.png' },
  {name:'Pepe nero in grani', unitMeasure:'kg', unitPrice:30.0000, vatCode: 0.2200, category: 'spezie', avatar:'ingredients.png' },
  {name:'Fior di sale di Guerande', unitMeasure:'kg', unitPrice:30.0000, vatCode: 0.0400, category: 'sale', avatar:'ingredients.png' },
  {name:'Basilico fresco in foglie', unitMeasure:'kg', unitPrice:40.0000, vatCode: 0.0400, category: 'erbe aromatiche', avatar:'ingredients.png' },
  {name:'Acido tartarico', unitMeasure:'kg', unitPrice:30.0000, vatCode: 0.1000, category: 'acidificanti', avatar:'ingredients.png' },
  {name:'Letchi in purea', unitMeasure:'kg', unitPrice:12.0000, vatCode: 0.1000, category: 'frutta purea', avatar:'ingredients.png' },
  {name:'Glucosio (sciroppo)', unitMeasure:'kg', unitPrice:6.0000, vatCode: 0.0400, category: 'zuccheri', avatar:'ingredients.png' },
  {name:'Essenza di rosa', unitMeasure:'kg', unitPrice:47.0000, vatCode: 0.2200, category: 'aromi', avatar:'ingredients.png' },
  {name:'Zucchero neige decor', unitMeasure:'kg', unitPrice:22.0000, vatCode: 0.0400, category: 'zuccheri', avatar:'ingredients.png' },
  {name:'Fragole fresche', unitMeasure:'kg', unitPrice:12.0000, vatCode: 0.0400, category: 'Frutta fresca', avatar:'ingredients.png' },
  {name:'colorante rosso carminio', unitMeasure:'kg', unitPrice:500.0000, vatCode: 0.2200, category: 'coloranti', avatar:'ingredients.png' },
  {name:'colorante rosso fragola', unitMeasure:'kg', unitPrice:50.0000, vatCode: 0.2200, category: 'coloranti', avatar:'ingredients.png' },
  {name:'Albume in polvere', unitMeasure:'kg', unitPrice:20.0000, vatCode: 0.2200, category: 'uova', avatar:'ingredients.png' },
  {name:'Litchi sciroppati', unitMeasure:'kg', unitPrice:7.0000, vatCode: 0.2200, category: 'frutta sciroppata', avatar:'ingredients.png' },
  {name:'Copertura bianca ivoire Valrhona', unitMeasure:'kg', unitPrice:27.0000, vatCode: 0.2200, category: 'cioccolato', avatar:'ingredients.png' },
  {name:'Nappage neutro', unitMeasure:'kg', unitPrice:10.0000, vatCode: 0.2200, category: 'coperture', avatar:'ingredients.png' },
  {name:'Lamponi freschi', unitMeasure:'kg', unitPrice:15.0000, vatCode: 0.0400, category: 'Frutta fresca', avatar:'ingredients.png' },
  {name:'Pasta di pistacchio', unitMeasure:'kg', unitPrice:45.0000, vatCode: 0.2200, category: 'paste', avatar:'ingredients.png' },
  {name:'Burro salato', unitMeasure:'kg', unitPrice:15.0000, vatCode: 0.1000, category: 'burro', avatar:'ingredients.png' },
  {name:'Essenza di bergamotto', unitMeasure:'kg', unitPrice:200.0000, vatCode: 0.2200, category: 'aromi', avatar:'ingredients.png' },
  {name:'Essenza di violetta', unitMeasure:'kg', unitPrice:200.0000, vatCode: 0.2200, category: 'aromi', avatar:'ingredients.png' },
  {name:'Confettura ai frutti di bosco', unitMeasure:'kg', unitPrice:15.0000, vatCode: 0.1000, category: 'confetture', avatar:'ingredients.png' },
  {name:'Farina per croissant', unitMeasure:'kg', unitPrice:1.5000, vatCode: 0.0400, category: 'farine', avatar:'ingredients.png' },
  {name:'Malto in polvere', unitMeasure:'kg', unitPrice:10.0000, vatCode: 0.1000, category: 'lieviti', avatar:'ingredients.png' },
  {name:'Lievito chimico', unitMeasure:'kg', unitPrice:15.0000, vatCode: 0.1000, category: 'lieviti', avatar:'ingredients.png' },
  {name:'Acqua di fiori di arancio', unitMeasure:'kg', unitPrice: 21.7000, vatCode: 0.2200, category: 'aromi', avatar:'ingredients.png'},
  {name:'Noci sgusciate', unitMeasure:'kg', unitPrice:25.0000, vatCode: 0.1000, category: 'frutta secca', avatar:'ingredients.png' },
  {name:'Scorza di arancia candita', unitMeasure:'kg', unitPrice:20.0000, vatCode: 0.0400, category: 'canditi', avatar:'ingredients.png' },
  {name:'Arancia fresca', unitMeasure:'kg', unitPrice:2.5000, vatCode: 0.0400, category: 'Frutta fresca', avatar:'ingredients.png' },
  {name:'Miele millefiori', unitMeasure:'kg', unitPrice:15.0000, vatCode: 0.1000, category: 'Miele', avatar:'ingredients.png' },
  {name:'Mandorle sfilettate', unitMeasure:'kg', unitPrice:20.0000, vatCode: 0.1000, category: 'frutta secca', avatar:'ingredients.png' },
  {name:'Aceto di vino bianco', unitMeasure:'kg', unitPrice:3.0000, vatCode: 0.1000, category: 'Aceto', avatar:'ingredients.png' },
  {name:'rabarbaro purea congelato', unitMeasure:'kg', unitPrice:12.0000, vatCode: 0.1000, category: 'frutta purea', avatar:'ingredients.png' },
  {name:'Uva fresca', unitMeasure:'kg', unitPrice:4.0000, vatCode: 0.0400, category: 'Frutta fresca', avatar:'ingredients.png' },
  {name:'Mirtillo fresco', unitMeasure:'kg', unitPrice:10.0000, vatCode: 0.0400, category: 'Frutta fresca', avatar:'ingredients.png' },
  {name:'Mora fresca', unitMeasure:'kg', unitPrice:12.0000, vatCode: 0.0400, category: 'Frutta fresca', avatar:'ingredients.png' },
  {name:'Zucchero Muscovado', unitMeasure:'kg', unitPrice:4.9300, vatCode: 0.1000, category: 'Zucchero', avatar:'ingredients.png'},
  {name:'Tè alla violetta in foglie', unitMeasure:'kg', unitPrice:40.0000, vatCode: 0.1000, category: 'Te e tisane'}
]

const foods = _.sortBy(rawFoods, o => o.name.toUpperCase())

export {
  foods,
}
